language: c

services:
  - docker

script:
- docker run --rm dockcross/web-wasm > ./dockcross
- chmod +x ./dockcross
- mv ./dockcross ~/bin/
- chmod +x doBuild.sh
- sudo apt-get install -y zlib1g-dev
- dockcross bash -c './doBuild.sh'

after_success:
- curl -L -k https://github.com/c4milo/github-release/releases/download/v1.0.8/github-release_v1.0.8_linux_amd64.tar.gz | tar -xz
- ./github-release intrigus/gdx-freetype-gwt-gen v.${TRAVIS_COMMIT} "master" "FreeType-js for use with libgdx" "freetype.j*"
